version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restapi_constanta
    volumes:
      - ./internal/pg/data:/var/lib/postgresql/data

  resapi:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: restapi
    ports:
      - "8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      PG_URL: "postgres://postgres:postgres@postgres/restapi_constanta?sslmode=disable"
      PG_MIGRATIONS_PATH: "file://../../internal/migrations"
