version: '3.9'

services:

  db:
    restart: always
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./internal/pg/data:/var/lib/postgresql/data

  test_db:
    depends_on:
      - db
    restart: always
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/docker-entrypoint-initdb.d/init.sql
      - ./internal/pgtest/data:/var/lib/postgresql/data

  resapi:
    depends_on: 
      - test_db
    build: ./
    ports: 
      - "8080:8080"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    command: ./wait-for-postgres.sh db ./apiserver
