bind_addr = ":8080"
log_level = "debug"
database_url = "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
# database_url = "user=postgres password=postgres port=5432 host=localhost dbname=restapi_constanta sslmode=disable"
session_key = "2hqgfLblkp9nmK04Lj4tcQH4bITAogeK"
pg_migrations_path = "file://internal/app/store/migrations"
pg_url = "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
pg_test = "postgres://postgres:postgres@test_db:5432/postgres_test?sslmode=disable"