bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost dbname=restapi_constanta sslmode=disable"
session_key = "2hqgfLblkp9nmK04Lj4tcQH4bITAogeK"
pg_migrations_path = "file://internal/app/store/migrations"
pg_url = "postgres://localhost/restapi_constanta?sslmode=disable"
pg_test = "postgres://localhost/constanta_test?sslmode=disable"